// 1)
db.products.find({}, { name: 1, price: 1, _id: 0 })
db.products.find({}, { dimensions: 0 })
db.products.find({}, { name: 1, rating: 1, _id: 0 })
db.products.find({}, { "dimensions.width": 1, "dimensions.height": 1, _id: 0 })
db.products.find({ in_stock: true }, { name: 1, in_stock: 1, _id: 0 })

// 2)
db.products.find().limit(5)
db.products.find({ price: { $gt: 100 } }).limit(10)
db.products.find({ rating: { $ne: null } }).limit(3)
db.products.find({}, { name: 1, _id: 0 }).limit(7)
db.products.find().sort({ price: 1 }).limit(5)

// 3)
db.products.countDocuments()
db.products.countDocuments({ in_stock: true })
db.products.countDocuments({ price: { $gt: 200 } })
db.products.countDocuments({ rating: { $exists: true, $ne: null } })

// 4)
db.products.find({ rating: { $exists: true } })
db.products.find({ rating: { $exists: false } })
db.products.find({ "dimensions.depth": { $exists: true } })
db.products.find({ tags: { $exists: true } })
db.products.find({ discount: { $exists: false } })